import { Category } from "../types";

export const categories: Category[] = [
  {
    name: "AI",
    slug: "ai",
    description: "Artificial Intelligence and Machine Learning products",
    tags: [
      "AI Assistants",
      "Machine Learning",
      "Computer Vision",
      "Natural Language Processing",
      "Generative AI",
      "AI Agents",
    ],
  },
  {
    name: "Development",
    slug: "development",
    description: "Developer tools and infrastructure",
    tags: [
      "Developer Tools",
      "Code Editors",
      "DevOps",
      "Testing",
      "Cloud Infrastructure",
      "Databases",
      "APIs",
      "Authentication",
      "Monitoring",
    ],
  },
  {
    name: "Productivity",
    slug: "productivity",
    description: "Productivity and workflow tools",
    tags: [
      "Task Management",
      "Note Taking",
      "Calendar",
      "Project Management",
      "Documentation",
      "Collaboration",
      "Automation",
      "File Storage",
      "Screen Recording",
    ],
  },
  {
    name: "Marketing & Sales",
    slug: "marketing-sales",
    description: "Marketing and sales tools",
    tags: [
      "Email Marketing",
      "SEO",
      "Social Media",
      "Advertising",
      "CRM",
      "Lead Generation",
      "Analytics",
      "Surveys",
    ],
  },
  {
    name: "Design & Creative",
    slug: "design-creative",
    description: "Design and creative tools",
    tags: [
      "UI/UX Design",
      "Graphic Design",
      "Prototyping",
      "Branding",
      "Photo Editing",
      "Video Editing",
      "Animation",
      "Design Resources",
    ],
  },
  {
    name: "Finance",
    slug: "finance",
    description: "Financial tools and services",
    tags: [
      "Accounting",
      "Invoicing",
      "Payments",
      "Banking",
      "Investing",
      "Budgeting",
      "Payroll",
      "Crypto",
    ],
  },
  {
    name: "Content & Media",
    slug: "content-media",
    description: "Content creation and media tools",
    tags: [
      "Blogging",
      "Podcasting",
      "Video Production",
      "Audio Editing",
      "Streaming",
      "Newsletter",
      "Writing",
    ],
  },
  {
    name: "Social & Community",
    slug: "social-community",
    description: "Social and community platforms",
    tags: [
      "Social Media",
      "Community",
      "Forums",
      "Messaging",
      "Networking",
      "Video Calling",
    ],
  },
  {
    name: "Analytics & Data",
    slug: "analytics-data",
    description: "Analytics and data tools",
    tags: [
      "Analytics",
      "Business Intelligence",
      "Data Visualization",
      "Data Science",
    ],
  },
  {
    name: "Education & Learning",
    slug: "education-learning",
    description: "Education and learning platforms",
    tags: [
      "Online Courses",
      "Tutoring",
      "Language Learning",
      "Student Tools",
    ],
  },
  {
    name: "Startup & Business",
    slug: "startup-business",
    description: "Startup and business tools",
    tags: [
      "Startup Tools",
      "No-Code Builders",
      "Templates",
      "HR",
      "Hiring",
      "Freelancing",
    ],
  },
  {
    name: "E-commerce",
    slug: "ecommerce",
    description: "E-commerce and retail tools",
    tags: [
      "Online Stores",
      "Marketplace",
      "Inventory",
      "Shipping",
      "Payments",
    ],
  },
  {
    name: "Health & Wellness",
    slug: "health-wellness",
    description: "Health and wellness apps",
    tags: [
      "Fitness",
      "Mental Health",
      "Nutrition",
      "Meditation",
      "Health Tracking",
    ],
  },
  {
    name: "Travel & Lifestyle",
    slug: "travel-lifestyle",
    description: "Travel and lifestyle apps",
    tags: [
      "Travel Planning",
      "Booking",
      "Maps",
      "Weather",
      "Real Estate",
    ],
  },
  {
    name: "Web3",
    slug: "web3",
    description: "Web3 and blockchain tools",
    tags: [
      "Blockchain",
      "NFT",
      "DeFi",
      "Smart Contracts",
    ],
  },
  {
    name: "Extensions & Plugins",
    slug: "extensions-plugins",
    description: "Browser extensions and app plugins",
    tags: [
      "Browser Extensions",
      "App Plugins",
      "Templates",
    ],
  },
].map((cat) => ({
  ...cat,
  slug: cat.slug || cat.name.toLowerCase().replace(/\s+/g, "-").replace(/&/g, "and"),
}));

