export interface TagCategory {
  name: string;
  tags: string[];
}

export const tags: TagCategory[] = [
  {
    name: "AI",
    tags: [
      "AI",
      "Artificial Intelligence",
      "Machine Learning",
      "Deep Learning",
      "GPT",
      "LLM",
      "Natural Language Processing",
      "Computer Vision",
      "Generative AI",
      "AI Chatbots",
      "AI Assistant",
      "Conversational AI",
      "AI Notetakers",
      "AI Presentation Software",
      "AI Characters",
      "AI Generative Media",
      "AI Headshot Generators",
      "AI Content Detection",
      "Predictive AI",
    ],
  },
  {
    name: "Development",
    tags: [
      "Developer Tools",
      "Code Editors",
      "AI Code Editors",
      "AI Coding Agents",
      "AI Code Testing",
      "IDE",
      "API",
      "Git",
      "Git Clients",
      "CI/CD",
      "DevOps",
      "Debugging",
      "Testing",
      "Testing and QA",
      "Code Review",
      "Code Review Tools",
      "Version Control",
      "Deployment",
      "Monitoring",
      "Observability",
      "Infrastructure",
      "Cloud Computing",
      "Cloud",
      "AWS",
      "Azure",
      "Google Cloud",
      "Hosting",
      "Web Hosting",
      "Serverless",
      "Databases",
      "Backend",
      "AI Databases",
      "Analytics Databases",
      "Headless CMS",
      "Static Site Generators",
      "Command Line Tools",
      "Terminals",
      "Issue Tracking",
      "Authentication",
      "Identity",
      "Automation Tools",
      "Browser Automation",
      "Real-time Collaboration",
      "Unified API",
      "VPN",
      "Standup Bots",
      "Video Hosting",
      "Vibe Coding Tools",
      "A/B Testing Tools",
    ],
  },
  {
    name: "Productivity",
    tags: [
      "Productivity",
      "Task Management",
      "Time Tracking",
      "Note Taking",
      "Writing Apps",
      "Calendar",
      "Calendar Apps",
      "Scheduling",
      "Project Management",
      "Todo",
      "Organizer",
      "Workflow",
      "Automation",
      "Focus",
      "Collaboration",
      "Team Collaboration",
      "Team",
      "Communication",
      "Slack",
      "Microsoft Teams",
      "Team Chat",
      "Remote Work",
      "Remote Tools",
      "Distributed Team",
      "Work from Home",
      "Virtual Office",
      "Notion",
      "Documentation",
      "Wiki",
      "Knowledge Base",
      "CMS",
      "Content Management",
      "Meeting Software",
      "Video Conferencing",
      "App Switcher",
      "Email Clients",
      "File Storage",
      "File Sharing",
      "E-signature",
      "Password Managers",
      "PDF Editor",
      "Resume Tools",
      "Screenshots",
      "Screen Recording",
      "Search",
      "Security Software",
      "Spreadsheets",
      "Compliance",
      "Customer Support",
      "Writing Assistants",
      "Legal Services",
      "Presentation Software",
      "Product Demo",
      "Ad Blockers",
      "Web Browsers",
    ],
  },
  {
    name: "Marketing & Sales",
    tags: [
      "Marketing",
      "Growth",
      "Email Marketing",
      "Social Media Marketing",
      "Content Marketing",
      "Lead Generation",
      "Sales",
      "AI Sales Tools",
      "Sales Enablement",
      "Sales Training",
      "Conversion",
      "A/B Testing",
      "Campaign Management",
      "SEO",
      "SEO Tools",
      "Search Engine Optimization",
      "Keywords",
      "Keyword Research",
      "Ranking",
      "Backlinks",
      "Advertising",
      "Advertising Tools",
      "Ads",
      "PPC",
      "Google Ads",
      "Facebook Ads",
      "Display Ads",
      "CRM",
      "CRM Software",
      "Customer Relationship Management",
      "Pipeline",
      "Salesforce",
      "Newsletter",
      "Email Campaign",
      "Substack",
      "Mailchimp",
      "Landing Page Builder",
      "Marketing Automation",
      "Influencer Marketing",
      "Affiliate Marketing",
      "Customer Loyalty",
      "Survey",
      "Form Builder",
      "GEO Tools",
      "Website Analytics",
    ],
  },
  {
    name: "Design & Creative",
    tags: [
      "UI",
      "UX",
      "Design",
      "Interface Design",
      "Figma",
      "Prototyping",
      "Wireframing",
      "User Research",
      "Design System",
      "Interaction Design",
      "User Testing",
      "Branding",
      "Brand",
      "Identity",
      "Logo",
      "Visual Identity",
      "Brand Strategy",
      "Framer",
      "Visual Design",
      "Interactive",
      "Animation",
      "3D",
      "Graphic Design",
      "Photo Editing",
      "Video Editing",
      "Camera Apps",
      "Mobile Editing",
      "Background Removal",
      "Design Inspiration",
      "Design Mockups",
      "Design Resources",
      "Digital Whiteboards",
      "Icon Sets",
      "Stock Photos",
      "Wallpapers",
      "UI Frameworks",
      "Avatar Generators",
      "Music Generation",
      "Space Design",
    ],
  },
  {
    name: "Finance",
    tags: [
      "Fintech",
      "Finance",
      "Investment",
      "Investing",
      "Stock Trading",
      "VC",
      "Venture Capital",
      "Trading",
      "Portfolio Management",
      "Fundraising",
      "Financial Planning",
      "Wealth Management",
      "Retirement Planning",
      "Payments",
      "Payment Processing",
      "Banking",
      "Online Banking",
      "Neobanks",
      "Stripe",
      "PayPal",
      "Money Transfer",
      "Digital Wallet",
      "Accounting",
      "Accounting Software",
      "Bookkeeping",
      "Invoicing",
      "Expenses",
      "Tax",
      "Tax Preparation",
      "Billing",
      "QuickBooks",
      "Budgeting",
      "Savings",
      "Credit Score",
      "Payroll",
      "Treasury Management",
      "Startup Incorporation",
      "Startup Financial Planning",
    ],
  },
  {
    name: "Content & Media",
    tags: [
      "Blog",
      "Blogging",
      "Blogging Platforms",
      "Content",
      "CMS",
      "WordPress",
      "Writing",
      "Publishing",
      "Content Management",
      "Podcast",
      "Podcasting",
      "Audio",
      "Recording",
      "Streaming",
      "Live Streaming",
      "Content Creation",
      "Broadcasting",
      "Music",
      "Music Software",
      "Sound",
      "Production",
      "Music Creation",
      "Audio Editing",
      "Video",
      "Media",
      "Social Audio",
      "Microblogging",
      "Newsletter Platforms",
      "Photo Sharing",
    ],
  },
  {
    name: "Social & Community",
    tags: [
      "Social Media",
      "Social Networking",
      "Twitter",
      "Instagram",
      "LinkedIn",
      "Facebook",
      "TikTok",
      "Social Scheduling",
      "Social Media Management",
      "Social Analytics",
      "Influencer Marketing",
      "Community Management",
      "Community",
      "Forum",
      "Discussion",
      "Social Network",
      "Groups",
      "Membership",
      "Membership Software",
      "Engagement",
      "Dating",
      "Professional Networking",
      "Messaging",
      "Social Bookmarking",
      "Link in Bio",
      "Video Calling",
      "Voice Calling",
      "Safety",
      "Privacy",
    ],
  },
  {
    name: "Analytics & Data",
    tags: [
      "Analytics",
      "Data",
      "Data Analysis",
      "Business Intelligence",
      "Reporting",
      "Dashboard",
      "Metrics",
      "Data Visualization",
      "Statistics",
      "KPIs",
      "Insights",
      "Big Data",
      "Data Science",
      "AI Data Scientist",
      "Website Analytics",
      "Analytics Databases",
    ],
  },
  {
    name: "Education & Learning",
    tags: [
      "Education",
      "EdTech",
      "E-Learning",
      "Online Learning",
      "Online Courses",
      "Learning Management",
      "Tutoring",
      "Student Tools",
      "Training",
      "Assessment",
      "Course",
      "Teaching",
      "Learning",
      "Tutorial",
      "Instruction",
      "Curriculum",
      "Book",
      "Books",
      "E-book",
      "Reading",
      "Language Learning",
    ],
  },
  {
    name: "Startup & Business",
    tags: [
      "Startup",
      "Startup Tools",
      "Startup Communities",
      "Venture Studio",
      "Company Builder",
      "Incubator",
      "Accelerator",
      "Founder Resources",
      "MVP",
      "Minimum Viable Product",
      "App Builder",
      "Website Builder",
      "Rapid Prototyping",
      "Landing Page",
      "Starter Kit",
      "Template",
      "Boilerplate",
      "Framework",
      "Quick Start",
      "Hiring",
      "Hiring Software",
      "HR",
      "Human Resources",
      "Recruitment",
      "Talent Management",
      "Employee Management",
      "Payroll",
      "Benefits",
      "Performance",
      "Job Board",
      "Jobs",
      "Career",
      "Employment",
      "Operations",
      "Agency",
      "Services",
      "Consulting",
      "Freelancer",
      "Freelance",
      "Contractor",
      "Client Management",
      "Event Software",
      "Virtual Events",
    ],
  },
  {
    name: "E-commerce & Retail",
    tags: [
      "E-commerce",
      "Ecommerce Platforms",
      "Marketplace",
      "Marketplace Sites",
      "Platform",
      "Vendor",
      "Seller",
      "Buyer",
      "Transactions",
      "Multi-vendor",
      "Shopping",
      "Online Store",
      "Logistics",
      "Supply Chain",
      "Shipping",
      "Inventory",
      "Warehouse",
      "Delivery",
      "Fulfillment",
      "Payment Processors",
      "Shopify Apps",
    ],
  },
  {
    name: "Health & Wellness",
    tags: [
      "Health",
      "Wellness",
      "Fitness",
      "Workout",
      "Mental Health",
      "Therapy",
      "Meditation",
      "Sleep",
      "Nutrition",
      "Habit Tracking",
      "Activity Tracking",
      "Lifestyle",
      "Self Care",
      "Personal Development",
      "Medical",
      "Health Insurance",
      "Senior Care",
    ],
  },
  {
    name: "Travel & Outdoors",
    tags: [
      "Travel",
      "Travel Planning",
      "Travel Apps",
      "Flight Booking",
      "Hotel Booking",
      "Short Term Rentals",
      "Travel Insurance",
      "Maps",
      "GPS",
      "Weather",
      "Hiking",
      "Camping",
      "Outdoors",
      "Real Estate",
    ],
  },
  {
    name: "Web3 & Crypto",
    tags: [
      "Web3",
      "Blockchain",
      "Cryptocurrency",
      "Crypto",
      "Crypto Wallets",
      "Crypto Exchanges",
      "Crypto Tools",
      "NFT",
      "NFT Marketplaces",
      "NFT Creation",
      "DeFi",
      "DAOs",
      "Smart Contracts",
      "Decentralized",
    ],
  },
  {
    name: "LLMs & AI Agents",
    tags: [
      "LLM",
      "Large Language Models",
      "Foundation Models",
      "AI Chatbots",
      "AI Infrastructure",
      "LLM Developer Tools",
      "LLM Fine Tuning",
      "Prompt Engineering",
      "AI Metrics",
      "AI Evaluation",
      "AI Agents",
      "AI Agent Automation",
      "AI Chief Of Staff",
      "AI Data Scientist",
      "AI Designer",
      "AI Engineer",
      "AI SDR",
    ],
  },
  {
    name: "Voice & Speech AI",
    tags: [
      "Voice AI",
      "AI Voice Agents",
      "Voice Agent Infrastructure",
      "Realtime Voice AI",
      "Text-to-Speech",
      "TTS",
      "Speech Recognition",
      "AI Dictation",
      "Transcription",
      "Translation",
    ],
  },
  {
    name: "No-Code Platforms",
    tags: [
      "No Code",
      "Low Code",
      "No-Code AI Agent Builder",
      "No-Code App Builder",
      "No-Code Website Builder",
      "Visual Builder",
      "Website Builder",
      "App Builder",
      "Automation",
      "Workflow Builder",
      "Drag and Drop",
      "Visual Development",
    ],
  },
  {
    name: "Directories & Discovery",
    tags: [
      "Directory",
      "Aggregator",
      "Listing",
      "Curated",
      "Discovery",
      "Collection",
      "Resource",
      "Index",
      "Open Source",
      "OSS",
      "GitHub",
      "Repository",
      "News",
      "Crowdfunding",
    ],
  },
  {
    name: "Product Extensions",
    tags: [
      "Chrome Extensions",
      "Figma Plugins",
      "Figma Templates",
      "Notion Templates",
      "Slack Apps",
      "Twitter Apps",
      "WordPress Plugins",
      "WordPress Themes",
      "Shopify Apps",
    ],
  },
  {
    name: "Physical Products",
    tags: [
      "Hardware",
      "Wearables",
      "Webcams",
      "Fitness Equipment",
      "Furniture",
      "Games",
      "Toys",
      "Books",
      "IoT",
      "Internet of Things",
      "Smart Devices",
      "Connected Devices",
      "Sensors",
    ],
  },
  {
    name: "Family & Kids",
    tags: [
      "Family",
      "Family Care",
      "Kids",
      "Apps for Kids",
      "Pregnancy",
      "Parenting",
      "Children",
      "Education for Kids",
    ],
  },
  {
    name: "Sustainability",
    tags: [
      "GreenTech",
      "Sustainability",
      "Environment",
      "Climate",
      "Renewable Energy",
      "Carbon",
      "Eco-friendly",
      "Green Technology",
      "Environmental",
    ],
  },
];
