export interface TagCategory {
  name: string;
  tags: string[];
}

export const TAG_CATEGORIES: TagCategory[] = [
  {
    name: "AI & Assistants",
    tags: [
      "AI",
      "Artificial Intelligence",
      "Chatbot",
      "Virtual Assistant",
      "Machine Learning",
      "GPT",
      "LLM",
      "Natural Language Processing",
      "AI Assistant",
      "Conversational AI",
      "Generative AI",
    ],
  },
  {
    name: "Productivity Tools",
    tags: [
      "Productivity",
      "Task Management",
      "Time Tracking",
      "Note Taking",
      "Calendar",
      "Project Management",
      "Todo",
      "Organizer",
      "Workflow",
      "Automation",
      "Focus",
    ],
  },
  {
    name: "Marketing & Growth",
    tags: [
      "Marketing",
      "Growth",
      "Email Marketing",
      "Social Media Marketing",
      "Content Marketing",
      "Lead Generation",
      "CRM",
      "Sales",
      "Conversion",
      "A/B Testing",
      "Campaign Management",
    ],
  },
  {
    name: "Dev Tools",
    tags: [
      "Developer Tools",
      "API",
      "Git",
      "CI/CD",
      "DevOps",
      "Debugging",
      "Testing",
      "Code Review",
      "Version Control",
      "Deployment",
      "Monitoring",
      "Infrastructure",
    ],
  },
  {
    name: "Tech",
    tags: [
      "Technology",
      "Software",
      "Platform",
      "Tool",
      "Application",
      "Solution",
      "Service",
      "System",
      "Infrastructure",
      "Cloud",
    ],
  },
  {
    name: "Social Media Tools",
    tags: [
      "Social Media",
      "Twitter",
      "Instagram",
      "LinkedIn",
      "Facebook",
      "TikTok",
      "Content Creation",
      "Social Scheduling",
      "Social Analytics",
      "Influencer Marketing",
      "Community Management",
    ],
  },
  {
    name: "Lifestyle & Health",
    tags: [
      "Health",
      "Wellness",
      "Fitness",
      "Mental Health",
      "Meditation",
      "Sleep",
      "Nutrition",
      "Habit Tracking",
      "Lifestyle",
      "Self Care",
    ],
  },
  {
    name: "Analytics & Data",
    tags: [
      "Analytics",
      "Data",
      "Business Intelligence",
      "Reporting",
      "Dashboard",
      "Metrics",
      "Data Visualization",
      "Statistics",
      "KPIs",
      "Insights",
    ],
  },
  {
    name: "No Code",
    tags: [
      "No Code",
      "Low Code",
      "Visual Builder",
      "Website Builder",
      "App Builder",
      "Automation",
      "Workflow Builder",
      "Drag and Drop",
      "Visual Development",
    ],
  },
  {
    name: "SEO",
    tags: [
      "SEO",
      "Search Engine Optimization",
      "Keywords",
      "Ranking",
      "Backlinks",
      "Content Optimization",
      "Technical SEO",
      "Local SEO",
      "SEO Tools",
      "Analytics",
    ],
  },
  {
    name: "EdTech",
    tags: [
      "Education",
      "EdTech",
      "E-Learning",
      "Online Courses",
      "Learning Management",
      "Tutoring",
      "Student Tools",
      "Training",
      "Assessment",
      "Educational Technology",
    ],
  },
  {
    name: "Fintech & VC Tools",
    tags: [
      "Fintech",
      "Finance",
      "Investment",
      "VC",
      "Venture Capital",
      "Trading",
      "Portfolio Management",
      "Fundraising",
      "Financial Planning",
      "Wealth Management",
    ],
  },
  {
    name: "Directories & Aggregators",
    tags: [
      "Directory",
      "Aggregator",
      "Listing",
      "Curated",
      "Discovery",
      "Marketplace",
      "Collection",
      "Resource",
      "Index",
    ],
  },
  {
    name: "Startup builders",
    tags: [
      "Startup",
      "Venture Studio",
      "Company Builder",
      "Incubator",
      "Accelerator",
      "Startup Tools",
      "Founder Resources",
      "Business Builder",
    ],
  },
  {
    name: "UI & UX Tools",
    tags: [
      "UI",
      "UX",
      "Design",
      "Figma",
      "Prototyping",
      "Wireframing",
      "User Research",
      "Design System",
      "Interaction Design",
      "User Testing",
    ],
  },
  {
    name: "Starter kits",
    tags: [
      "Starter Kit",
      "Template",
      "Boilerplate",
      "Framework",
      "Quick Start",
      "Sample",
      "Example",
      "Beginning",
    ],
  },
  {
    name: "Open Source Software",
    tags: [
      "Open Source",
      "OSS",
      "GitHub",
      "Community",
      "Free",
      "Contributors",
      "License",
      "Repository",
    ],
  },
  {
    name: "Community",
    tags: [
      "Community",
      "Forum",
      "Discussion",
      "Social Network",
      "Groups",
      "Membership",
      "User Community",
      "Engagement",
    ],
  },
  {
    name: "Marketplaces",
    tags: [
      "Marketplace",
      "E-commerce",
      "Platform",
      "Vendor",
      "Seller",
      "Buyer",
      "Transactions",
      "Multi-vendor",
    ],
  },
  {
    name: "HR Tools",
    tags: [
      "HR",
      "Human Resources",
      "Recruitment",
      "Hiring",
      "Talent Management",
      "Employee Management",
      "Payroll",
      "Benefits",
      "Performance",
    ],
  },
  {
    name: "MVP Site/App builders",
    tags: [
      "MVP",
      "Minimum Viable Product",
      "App Builder",
      "Website Builder",
      "Rapid Prototyping",
      "Quick Build",
      "Landing Page",
      "Prototype",
    ],
  },
  {
    name: "Team collaboration",
    tags: [
      "Collaboration",
      "Team",
      "Communication",
      "Slack",
      "Microsoft Teams",
      "Project Collaboration",
      "Team Chat",
      "Coordination",
      "Teamwork",
    ],
  },
  {
    name: "Job boards",
    tags: [
      "Job Board",
      "Jobs",
      "Recruitment",
      "Hiring",
      "Career",
      "Employment",
      "Talent",
      "Job Search",
      "Applicants",
    ],
  },
  {
    name: "Music Software",
    tags: [
      "Music",
      "Audio",
      "Sound",
      "Production",
      "Recording",
      "DJ",
      "Music Creation",
      "Audio Editing",
      "Streaming",
    ],
  },
  {
    name: "Cloud platforms",
    tags: [
      "Cloud",
      "AWS",
      "Azure",
      "Google Cloud",
      "Infrastructure",
      "Hosting",
      "Serverless",
      "Cloud Computing",
      "Deployment",
    ],
  },
  {
    name: "Newsletter",
    tags: [
      "Newsletter",
      "Email",
      "Subscribers",
      "Mailchimp",
      "Email Marketing",
      "Substack",
      "Email Campaign",
      "Email List",
    ],
  },
  {
    name: "Accounting Tools",
    tags: [
      "Accounting",
      "Bookkeeping",
      "Financial",
      "Invoicing",
      "Expenses",
      "Tax",
      "Billing",
      "Financial Management",
      "QuickBooks",
    ],
  },
  {
    name: "Freelancer Tools",
    tags: [
      "Freelancer",
      "Freelance",
      "Independent",
      "Contractor",
      "Gig Economy",
      "Client Management",
      "Project Billing",
      "Portfolio",
    ],
  },
  {
    name: "Branding services",
    tags: [
      "Branding",
      "Brand",
      "Identity",
      "Logo",
      "Design",
      "Marketing",
      "Brand Strategy",
      "Visual Identity",
    ],
  },
  {
    name: "Podcast",
    tags: [
      "Podcast",
      "Audio",
      "Recording",
      "Streaming",
      "Content Creation",
      "Audio Production",
      "Broadcasting",
    ],
  },
  {
    name: "Payments & Banking",
    tags: [
      "Payments",
      "Banking",
      "Payment Processing",
      "Stripe",
      "PayPal",
      "Financial Services",
      "Money Transfer",
      "Digital Wallet",
    ],
  },
  {
    name: "Remote Tools",
    tags: [
      "Remote",
      "Remote Work",
      "Distributed Team",
      "Work from Home",
      "Virtual Office",
      "Remote Collaboration",
      "Telecommuting",
    ],
  },
  {
    name: "Book",
    tags: [
      "Book",
      "E-book",
      "Reading",
      "Publishing",
      "Literature",
      "Digital Book",
      "Reading Platform",
    ],
  },
  {
    name: "Web3 apps",
    tags: [
      "Web3",
      "Blockchain",
      "Cryptocurrency",
      "NFT",
      "DeFi",
      "Smart Contracts",
      "Decentralized",
      "Crypto",
    ],
  },
  {
    name: "Notion Product",
    tags: [
      "Notion",
      "Note Taking",
      "Documentation",
      "Wiki",
      "Knowledge Base",
      "Workspace",
      "Productivity",
    ],
  },
  {
    name: "Course",
    tags: [
      "Course",
      "Teaching",
      "Learning",
      "Education",
      "Training",
      "Tutorial",
      "Instruction",
      "Curriculum",
    ],
  },
  {
    name: "CRM",
    tags: [
      "CRM",
      "Customer Relationship Management",
      "Sales",
      "Lead Management",
      "Customer Management",
      "Salesforce",
      "Pipeline",
      "Contacts",
    ],
  },
  {
    name: "Ads Platforms",
    tags: [
      "Advertising",
      "Ads",
      "PPC",
      "Google Ads",
      "Facebook Ads",
      "Ad Campaign",
      "Display Ads",
      "Advertising Platform",
    ],
  },
  {
    name: "Blogging Platform",
    tags: [
      "Blog",
      "Blogging",
      "Content",
      "CMS",
      "WordPress",
      "Writing",
      "Publishing",
      "Content Management",
    ],
  },
  {
    name: "Brainstorming Tools",
    tags: [
      "Brainstorming",
      "Ideation",
      "Mind Mapping",
      "Creative",
      "Ideas",
      "Collaboration",
      "Whiteboard",
      "Concept Mapping",
    ],
  },
  {
    name: "Framer Product",
    tags: [
      "Framer",
      "Design",
      "Prototyping",
      "UI",
      "Visual Design",
      "Interactive",
      "Animation",
    ],
  },
  {
    name: "IoT & Devices",
    tags: [
      "IoT",
      "Internet of Things",
      "Devices",
      "Smart Devices",
      "Hardware",
      "Connected Devices",
      "Sensors",
    ],
  },
  {
    name: "Logistics Tools",
    tags: [
      "Logistics",
      "Supply Chain",
      "Shipping",
      "Inventory",
      "Warehouse",
      "Delivery",
      "Fulfillment",
      "Operations",
    ],
  },
  {
    name: "GreenTech",
    tags: [
      "GreenTech",
      "Sustainability",
      "Environment",
      "Climate",
      "Renewable Energy",
      "Carbon",
      "Eco-friendly",
      "Green Technology",
    ],
  },
  {
    name: "ASO",
    tags: [
      "ASO",
      "App Store Optimization",
      "Mobile",
      "App Marketing",
      "App Store",
      "Mobile Marketing",
      "App Discovery",
    ],
  },
  {
    name: "Agency Services",
    tags: [
      "Agency",
      "Services",
      "Consulting",
      "Creative Agency",
      "Digital Agency",
      "Agency Tools",
      "Client Services",
    ],
  },
  {
    name: "Other",
    tags: [
      "Other",
      "Miscellaneous",
      "Various",
      "General",
      "Tools",
      "Services",
      "Software",
    ],
  },
];
